// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from 'D:/temp/my-app/docs/components/carousel.md?type=frontmatter';
import { demoIndex as dmi0 } from 'D:/temp/my-app/docs/components/carousel.md?type=demo-index';

export const filesMeta = {
  'docs/components/carousel': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/temp/my-app/docs/components/carousel.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
